### ISSUE TITLE
Untrack build files and folders

### ISSUE THREAD

**Issue by gray-adeyi** [olawale1rty/SVY-319---Datum-Transfer#4]
Currently the repository tracks build files and folders which makes the repository size quite large for a small project. cloning the project too can be slow. I'm proposing that we stop tracking the build files and folders. The project can be built locally and the resulting binaries published in the releases.

**Comment by olawale1rty** [comment]
Agreed, I am currently facing an issue with pushing to GitHub due to large files after building for mac.

**Comment by gray-adeyi** [comment]
I see. I'll send in a pr later today to ignore those files and folders. so you can build locally. I'll build mine too locally and share the final binary with you so you can create a release. Do you think a cli is necessary?

**Comment by olawale1rty** [comment]
A CLI will work, I have fixed them already just still having issues with pushing out to GitHub. It kept complaining about large files.
![Screenshot 2024-02-05 at 14 22 41](https://github.com/olawale1rty/SVY-319---Datum-Transfer/assets/51883244/342a4941-fd62-4392-a196-02bc440b0c2b)

Also, I won't accept your PR for renaming because I changed it.

**Comment by gray-adeyi** [comment]
You can close the pr.

**Comment by gray-adeyi** [comment]
Can you send a screenshot of you project tree so I see what needs to be ignored?

**Comment by olawale1rty** [comment]
You changed your number already. Please call me.
![Screenshot 2024-02-05 at 14 29 16](https://github.com/olawale1rty/SVY-319---Datum-Transfer/assets/51883244/186e855d-adc9-4566-a8b2-3c15013c321a)

**Comment by gray-adeyi** [comment]
I've sent a pr with a fix
